import { I8n } from "./types.js";

export default {
  userNotInVoiceChannel: 'You are not in a voice channel',
  userNotInGuild: 'You are not in a guild',
  userNotInChanel: 'You are not in a channel',
  autoPlayResponse: 'Auto play is set to {status}',
  incorrectLoopMode: 'Incorrect loop mode the correct options are "single", "off", "all"',
  notEnoughArguments: 'Not enough arguments provided to the command {args}',
  loopModeNone: 'Loop mode: `None`',
  loopModeSingle: 'Loop mode: `Single`',
  loopModeAll: 'Loop mode: `All`',
  noSongsInQueue: 'No songs in queue',
  currentPlaying: 'Currently playing: {title} by {author}',
  pauseSongs: 'Paused all songs in queue',
  missingQuery: 'Missing query',
  noResults: 'No results found',
  addedPlaylistToQueue: 'Added **{num_of_songs}** songs to queue from playlist **{playlist_name}**',
  addedSongToQueue: 'Added **{title}** by **{author}** to queue',
  emptyQueue: 'Queue is empty',
  resumeSongs: 'Resumed all songs in queue',
  skippedSong: 'Skipped song in queue',
  stoppedPlaying: 'Stopped all songs in queue',
  settedVolume: 'Volume set to: {volume}',
  playingSongEmbed: 'Playing song: {title} by {author}',
  playingSong: 'Playing song: {title} by {author}',
  playerEnded: 'Player ended',
  playerDestroyed: 'Destroyed player due to inactivity.',
  cooldown: 'You have to wait {time} before using this command again.',
  missingPermissions: `You are missing the following permissions to run this command: {permissions}`,
  botMissingPermissions: `I am missing the following permissions to run this command: {permissions}`,
  commandNotAllowed: 'You are not allowed to use this command. Error code {code}',
  commandError: 'An error occurred while executing the command.\n\n-# Error code: {error}',
  lyricNotFound: 'Lyric not found',
  lyricEmbedTitle: 'Lyrics for {title} by {author}',
  noSongPlaying: 'No songs are currently playing',
  shuffledQueue: 'Shuffled queue',
} satisfies I8n